##### GENERAL SETTINGS

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g mouse on
set -g mode-keys vi
set -g set-clipboard on
set -g history-limit 10000
set -g default-terminal "screen-256color"

set-option -g default-command "/usr/bin/bash"
bind c new-window -c "#{pane_current_path}"

set -g base-index 1
setw -g pane-base-index 1

##### STATUS BAR

set -g status on
set -g status-interval 5
set -g status-justify centre
set -g status-left-length 60
set -g status-right-length 90
set -g status-position top 

set -g status-style "fg=colour250,bg=#262626"
set -g status-left ' #[fg=colour65]%Y-%m-%d | %a #[fg=colour65]|'
set -g status-right '#[fg=colour65]#(git -C "#{window_path}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "") #[fg=colour65]| #(whoami) #[fg=colour65]| #[fg=colour65]#(date +%R)'

##### WINDOW STYLE

setw -g window-status-format '#[fg=colour65] #I #W '
setw -g window-status-current-format '#[fg=colour65,bold]#[bg=#{@bg}] #I #W #[default]'
set -g window-style "bg=#262626"
set -g window-active-style "bg=#262626"

##### BORDER 

set -g pane-border-style "fg=colour65"
set -g pane-active-border-style "fg=colour65"

##### WINDOWS MOVEMENT

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

##### COPY TO SYSTEM CLIPBOARD WITH Y
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
