
vim.keymap.set("n", "<leader>og", function()
	local word = vim.fn.expand("<cword>")
	vim.cmd("silent! grep! -rn " .. vim.fn.shellescape(word) .. " **/*")
	vim.cmd("copen")
end, { desc = "Grep current word and open quickfix" })
vim.keymap.set("n", "<leader>qg", function()
	vim.fn.setqflist({})
	vim.cmd("cclose")
end, { desc = "Clear and close quickfix" })
